influxdb.settings:
  type: config_object
  label: 'InfluxDB Settings'
  mapping:
    logging:
      type: boolean
      label: 'Logging'
    schema:
      type: string
      label: 'Schema'
    host:
      type: string
      label: 'Host'
    port:
      type: integer
      label: 'Port'
    organization:
      type: string
      label: 'Organization'
    bucket:
      type: string
      label: 'Bucket'
    measurement:
      type: string
      label: 'Measurement'
    precision:
      type: string
      label: 'Precision'
    debug:
      type: boolean
      label: 'Debug'
